version: '3.8'
services:
  server:
    build: ./server
    ports:
      - 5000:5000
    restart: always
  
  database:
    # image: postgres:14-alpine
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=lhc123
      - POSTGRES_USER=lhc_user
      - POSTGRES_DB=lhc_db
