version: '3.8'
services:
  server:
    build: ./server
    ports:
      - 5000:5000
    restart: "no"
  
  database:
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database:/usr/src:ro
    environment:
      - POSTGRES_PASSWORD=lhc123
      - POSTGRES_USER=lhc_user
      - POSTGRES_DB=lhc_db
    restart: "no"
    
  pgadmin:
    image: dpage/pgadmin4
    restart: "no"
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: lhc@lhc.com
      PGADMIN_DEFAULT_PASSWORD: lhc123
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  api:
    build: ./api
    ports:
      - 8000:8000
    environment:
      - PORT=8000
    volumes:
      - ./api/app:/app:ro
    restart: "no"
