FROM nginx

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./public/*.html /usr/share/nginx/html
COPY ./public/*.css /usr/share/nginx/html
COPY ./public/*.js /usr/share/nginx/html
COPY ./public/assets/*.png /usr/share/nginx/html
